@startuml
!theme vibrant
actor User
participant ":Main" as Main
participant ":Parser" as Parser
participant ":ArgumentParser" as ArgumentParser
participant ":InputValidator" as InputValidator
participant ":SetBudgetCommand" as SetBudgetCommand
participant ":InvalidCommand" as InvalidCommand
participant ":ExpenseManager" as ExpenseManager
participant ":Ui" as Ui

activate Main

User -> Main : enters "setbudget a/500"

Main -> Parser : parse("setbudget a/500")
activate Parser

create ArgumentParser
Parser -> ArgumentParser : "a/500"
activate ArgumentParser
Parser -> ArgumentParser : getValue("a/")
ArgumentParser --> Parser : "500"
deactivate ArgumentParser

alt successful parsing

    Parser -> InputValidator : validateAmount("500", "setbudget")
    activate InputValidator
    InputValidator --> Parser : 500.0
    deactivate InputValidator

    create SetBudgetCommand
    Parser -> SetBudgetCommand : 500.0
    Parser --> Main : setBudgetCommand

else validation fails

    Parser -> InputValidator : validateAmount("invalid", "setbudget")
    activate InputValidator
    InputValidator -->> Parser : throws OrCashBuddyException
    deactivate InputValidator

    create InvalidCommand
    Parser -> InvalidCommand
    Parser --> Main : invalidCommand

end

deactivate Parser

alt command is SetBudgetCommand
    Main -> SetBudgetCommand : execute(expenseManager, ui)
    activate SetBudgetCommand

    SetBudgetCommand -> Ui : showSeparator()
    activate Ui
    deactivate Ui

    SetBudgetCommand -> ExpenseManager : setBudget(500.0)
    activate ExpenseManager
    deactivate ExpenseManager

    SetBudgetCommand -> Ui : showNewBudget(500.0)
    activate Ui
    Ui --> User : displays confirmation
    deactivate Ui

    SetBudgetCommand -> Ui : showSeparator()
    activate Ui
    deactivate Ui

    deactivate SetBudgetCommand

else command is InvalidCommand
    Main -> InvalidCommand : execute(expenseManager, ui)
    activate InvalidCommand

    InvalidCommand -> Ui : showSeparator()
    activate Ui
    deactivate Ui

    InvalidCommand -> Ui : showSetBudgetUsage()
    activate Ui
    Ui --> User : displays usage message
    deactivate Ui

    InvalidCommand -> Ui : showSeparator()
    activate Ui
    deactivate Ui

    deactivate InvalidCommand
end

deactivate Main
@enduml
